# Generated by Django 5.1.6 on 2025-02-25 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_alter_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('quantity_available', models.FloatField()),
                ('unit', models.CharField(choices=[('kg', 'Kilograms'), ('g', 'Grams'), ('l', 'Liters'), ('ml', 'Milliliters')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='FoodIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_needed', models.FloatField()),
                ('unit', models.CharField(choices=[('kg', 'Kilograms'), ('g', 'Grams'), ('l', 'Liters'), ('ml', 'Milliliters')], max_length=50)),
                ('food_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.fooditem')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.stock')),
            ],
            options={
                'unique_together': {('food_item', 'stock')},
            },
        ),
        migrations.AddField(
            model_name='fooditem',
            name='ingredients',
            field=models.ManyToManyField(through='menu.FoodIngredient', to='menu.stock'),
        ),
    ]
