# Generated by Django 5.1.6 on 2025-02-25 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_stock_foodingredient_fooditem_ingredients'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='reorder_level',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='stock',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
