# Generated by Django 5.1.6 on 2025-02-28 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_stock_reorder_level_stock_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='calories',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='food_photos/'),
        ),
    ]
